{
 "title": "Impact of attacks",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of bots",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{image=\"kralluk/ubuntu_for_ddos:v1.2\"} > (time() - 10)) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache UP/DOWN",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "apache_up{instance=~\"apache_exporter:9117\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache worker statuses",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apache_workers{instance=\"apache_exporter:9117\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache CPU load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "apache_cpuload{instance=~\"apache_exporter:9117\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received network traffic per bot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image=\"kralluk/ubuntu_for_ddos:v1.2\"}[$interval])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage per bot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\", image=\"kralluk/ubuntu_for_ddos:v1.2\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}